import { NavigationBar } from "@/components/NavigationBar";
import TanstackQueryProvider from "@/lib/providers/TanstackQueryProvider";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased bg-zinc-100`}>
                <div className="fixed top-0 w-full">
                    <div className="max-w-7xl mx-auto">
                        <NavigationBar />
                    </div>
                </div>
                <TanstackQueryProvider>{children}</TanstackQueryProvider>
            </body>
        </html>
    );
}
